### ISSUE TITLE
Getting error cannot open port while testing on emulator

### ISSUE THREAD

**Issue by Ayman-apps** [pawns-app/android-pawns-sdk-demo#4]
We are getting the below and unable to test, how to overcome it?
We are unable to test the sharing

 START_PAWNS_SERVICE
 Started service
Started sharing
D  event: starting error: null
D  event: not_running error: Unknown(reason=cant_open_port)

**Comment by Ayman-apps** [comment]
OK, will check. But we need some testing server that bypass some constraints to be able to test before releasing

**Comment by Ayman-apps** [comment]
Still the issue is there. Can you check internally providing some testing server

**Comment by laurynas-pawns** [comment]
If you wish to have a further discussion, please create a ticket for SDK support in our discord community channel. Thank you. 
Link: https://discord.gg/pawns-app-795598404217733131

**Comment by Ayman-apps** [comment]
My conclusion that it is not working with mobile data even if mobile data in coming from wifi. Is that the case?

**Comment by laurynas-pawns** [comment]
That is not true. While the majority of devices rely on home Wi-Fi connections, a substantial portion also actively uses mobile data.

**Comment by Ayman-apps** [comment]
Ok great, then this means you are not stopping mobile data at all.
I tried with 2 mobile operators in Egypt and it is not working even with their home sim solutions. This means that they are blocking your ports. I cannot find another reason. If you think there might be another reason let me know.

So my requirement here, can you bypass this blocking by the mobile operators by using another port, for example if cannot open port1 then try port2 or maybe. Can we test this?
Our major users reside in Egypt and this can justify we are getting low volumes. This is very important to handle.

**Comment by laurynas-pawns** [comment]
This issue is related to more than just android SDK. Could you please open a ticket in discord channel for further investigation and solutions? Thank you.
